### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by tanlucvn** [CroaBeast/SIR_Plugin#10]
[23:11:49 INFO]: [SIR] Enabling SIR v3.0.4
[23:11:49 ERROR]: Error occurred while enabling SIR v3.0.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/GameRule
        at me.croabeast.sir.plugin.world.WorldRule$Rule.<init>(WorldRule.java:133) ~[?:?]
        at me.croabeast.sir.plugin.world.WorldRule$Rule.<init>(WorldRule.java:117) ~[?:?]
        at me.croabeast.sir.plugin.world.WorldRule$BooleanRule.<init>(WorldRule.java:163) ~[?:?]
        at me.croabeast.sir.plugin.world.WorldRule$BooleanRule.<init>(WorldRule.java:160) ~[?:?]
        at me.croabeast.sir.plugin.world.WorldRule.fromBool(WorldRule.java:94) ~[?:?]
        at me.croabeast.sir.plugin.world.WorldRule.<clinit>(WorldRule.java:23) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_202]
        at me.croabeast.sir.plugin.SIRCollector.<init>(SIRCollector.java:17) ~[?:?]
        at me.croabeast.sir.plugin.SIRCollector.from(SIRCollector.java:32) ~[?:?]
        at me.croabeast.sir.plugin.file.CacheHandler.loadedHandlers(CacheHandler.java:37) ~[?:?]
        at me.croabeast.sir.plugin.file.CacheHandler.load(CacheHandler.java:53) ~[?:?]
        at me.croabeast.sir.plugin.SIRPlugin.onEnable(SIRPlugin.java:91) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.ClassNotFoundException: org.bukkit.GameRule
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Skyblock.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        ... 24 more
        
   I'm using paper 1.12.2

**Comment by CroaBeast** [comment]
Will fix it in next spigot release
